[package]
name = "calculator"
version = "0.1.0"
authors = ["devin782 <devin.wolford@oit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "^1", features = ["fltk-bundled"] }